name: Sync with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched
      
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/The-SEO-Hustler/static-pages-websites.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git merge upstream/main || true  # Avoid failure on conflicts

      - name: Reset src/lib/data.ts
        run: |
          git checkout HEAD src/lib/data.ts tailwind.config.ts
          git add src/lib/data.ts tailwind.config.ts
          git commit -m "Keep src/lib/data.ts and tailwind.config.ts intact" || true  # Avoid error if no changes

      - name: Configure Git for Authentication
        run: |
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/The-SEO-Hustler/test-template-fork.git

      - name: Push Changes to Fork
        run: git push origin main
