name: Sync Fork from Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/The-SEO-Hustler/static-pages-websites
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main --no-commit --strategy=ours
          git checkout HEAD -- src/lib/data.ts # Exclude changes to src/lib/data.ts
          git commit -m "Merge updates from upstream while ignoring src/lib/data.ts"

      - name: Push Changes to Fork
        run: git push origin main
